### ISSUE TITLE
mjlog2json

### ISSUE THREAD

**Issue by majiang** [VictorZXY/meowjong#1]
`data_processing/download_tenhou_game_logs.py` GETs from `tenhou.net/5/mjlog2json.cgi`:
https://github.com/VictorZXY/meowjong/blob/main/data_processing/download_tenhou_game_logs.py#L50-L66

According to Tenhou admin:
- [There was many accesses to `mjlog2json` from outside Japan around 2022/08/24 21:00–26:00 JST, which caused bad performance of the server.  Access XML files instead to download the logs](https://twitter.com/tsuno_s/status/1562561816760569857)
- [`mjlog2json` is now accecible only through proxy](https://twitter.com/tsuno_s/status/1562584452731371521)

I'm not sure if the accesses above relates to this repository, but the downloader should be fixed accordingly.

**Comment by VictorZXY** [comment]
Hi majiang,

The accesses above were not related to this repository (the last time this script was run was in late 2020). To avoid future disturbance to the Tenhou server by forks of this repository, I will soon make the converted dataset public and remove this script.
